# 테스트 모드
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/qnaService__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.tool.schema: DEBUG   # ★ DDL 생성/실패 로그 확인용
    org.hibernate.SQL: DEBUG

